spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 60s
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

ctrip:
  appid: 100003172
  
server:
  port: 2100
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log
